serviceName: go_test_exam
development: true
database:
  readDb:
    connectionString: "host=localhost user=root password=rootroot dbname=demo port=5432 sslmode=disable TimeZone=Asia/Ho_Chi_Minh"
    dbType: postgres
    migrationFilePath: migrations
    maxIdleConns: 100
    maxOpenConns: 200
    connMaxLifetime: 5
  writeDb:
    connectionString: "host=localhost user=root password=rootroot dbname=demo port=5432 sslmode=disable TimeZone=Asia/Ho_Chi_Minh"
    dbType: postgres
    migrationFilePath: migrations
    maxIdleConns: 100
    maxOpenConns: 200
    connMaxLifetime: 5
http:
  port: :5001
  development: true
  shutdownTimeout: 15
  resources: ["internal/resources/en.json",	"internal/resources/fr.json",	"internal/resources/vi.json"]
  allowOrigins: [ "http://locahost:8080" ]
grpc:
  port: :6001
  development: true
  maxConnectionIdle: 5
  timeout: 15
  maxConnectionAge: 5
  time: 10
client:
  userService: "localhost:5002"
  driverService: "localhost:5005"
  commonService: "localhost:5008"
logger:
  level: debug
  devMode: false
  encoder: json
tracing:
  enable: false
  serviceName: order_service
  hostPort: "localhost:4317"
  logSpans: false
kafka:
  dialer:
    username:
    password:
  config:
    brokers: [ "" ]
    groupID: 
    initTopics: false
    numWorker: 20
  topics:
    submitOrder:
      topicName:
      numPartitions: 10
      replicationFactor: 1
redis:
  addrs: ["localhost:6380"]
  password: ""
  db: 0
  poolSize: 300
heathcheck:
  interval: 10
  port: :7001
  goroutineThreshold: 1000
metrics:
  prometheusPath: /metrics
  prometheusPort: :8001
kakaomap:
  appRestKey: 
  mobilityApiEndpoint: 
  coord2regioncode: 
  address: 
  priority:
  timeChange:
authenticate:
  clientURI:
s3:
  path:
  reconci:
daservice:
  webApi: ""
  notification: /api/order/notification/new
  webhook: /api/order/webhook/new
  updateNotification: /api/order/notification
  cancelOrderNotification: /api/order/cancelnoti
  submitOrderNotification: /api/order/customer/notification
  getListCoupons: /api/coupon/list
  submitTipOrderAssigned: /api/order/notification/tip/assigned
cronjob:
  disable: true
  dispatchSms: 60
  stat: "0"
  FILELOC5: ""
featureflag:
  payment: disable
slackservice:
  channel: 
  username:
  urlSlackWebhook: 
