definitions:
  models.CreateCategoryReq:
    properties:
      category_name:
        type: string
    required:
    - category_name
    type: object
info:
  contact: {}
paths:
  /api/v1/category:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: get list categories
      tags:
      - Category
  /api/v1/product/search:
    get:
      consumes:
      - application/json
      parameters:
      - description: CreateCategoryReq
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/models.CreateCategoryReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: search products with filter and return pagination
      tags:
      - Product
  /api/v1/products:
    get:
      consumes:
      - application/json
      parameters:
      - description: CreateCategoryReq
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/models.CreateCategoryReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: search products with filter and return pagination
      tags:
      - Supplier
swagger: "2.0"
